apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.3.3
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: true
      volumeMounts:
      - mountPath: /tmp
        name: volume-0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER
          value: 127.0.0.1:2181

    - name: kafka
      image: confluentinc/cp-server:7.3.3
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: true
      volumeMounts:
      - mountPath: /tmp
        name: volume-0
      env:
      - name: KAFKA_SERVER
        value: 127.0.0.1:9092
      - name: KAFKA_BROKER_ID
        value: "1"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - name: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://127.0.0.1:29092,PLAINTEXT_HOST://127.0.0.1:9092
      - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
        value: http://127.0.0.1:8081

    - name: schema-registry
      image: confluentinc/cp-schema-registry:7.3.3
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      tty: true
      volumeMounts:
      - mountPath: /tmp
        name: volume-0
      env:
      - name: SCHEMA_REGISTRY_HOST_NAME
        value: schema-registry
      - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
        value: '127.0.0.1:29092'
      - name: SCHEMA_REGISTRY_LISTENERS
        value: http://0.0.0.0:8081

    - name: golang
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      tty: true
      resources:
        requests:
          memory: 12Gi
          cpu: "4"
        limits:
          memory: 16Gi
          cpu: "6"
    - name: net-tool
      image: wbitt/network-multitool
      tty: true
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
    - name: report
      image: hub.pingcap.net/jenkins/python3-requests:latest
      tty: true
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
